language: R
sudo: false
cache: packages

notifications:
  email:
    - alexadner.lange@uni-goettingen.de

addons:
  apt:
    packages:
      - libgsl-dev
os:
  - windows
  - linux
  - osx

script:
  - |
    R CMD build .
    travis_wait 100 R CMD check svars_1.2.2.tar.gz
