install: travis_wait 30 mvn install
sudo: required

language: R
cache: packages

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq default-jdk maven

addons:
  apt:
    packages:
      - libgsl0-dev

