language: R
sudo: false
cache: packages

notifications:
  email:
    - alexadner.lange@uni-goettingen.de

addons:
  apt:
    packages:
      - libgsl-dev

script:
  - |
    R CMD build .
    travis_wait 100 R CMD check *tar.gz
